
name = "DashCalendarTimeline"
uuid = "1b08a953-4be3-4667-9a23-d86b5adce07a"
authors = ["Waleed Malik <waleed@zenalytiks.com>"]
version = "0.0.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
