# AUTO GENERATED FILE - DO NOT EDIT

#' @export
''DashCalendarTimeline <- function(id=NULL, boundsChangeData=NULL, buffer=NULL, canChangeGroup=NULL, canMove=NULL, canResize=NULL, canvasClickData=NULL, canvasContextMenuData=NULL, canvasDoubleClickData=NULL, clickTolerance=NULL, cursorMarkerStyle=NULL, customGroups=NULL, customGroupsContent=NULL, customItems=NULL, customItemsContent=NULL, customMarkers=NULL, defaultTimeEnd=NULL, defaultTimeStart=NULL, disableScroll=NULL, dragInfoLabel=NULL, dragInfoLabelStyle=NULL, dragSnap=NULL, draggingItemColor=NULL, groups=NULL, groupsClass=NULL, groupsStyle=NULL, itemClickData=NULL, itemContextMenuData=NULL, itemDimensions=NULL, itemDoubleClickData=NULL, itemHeightRatio=NULL, itemSelectData=NULL, itemTouchSendsClick=NULL, items=NULL, itemsClass=NULL, itemsStyle=NULL, lineHeight=NULL, maxZoom=NULL, minResizeWidth=NULL, minZoom=NULL, primaryDateHeaderHeight=NULL, primaryDateHeaderLabelFormat=NULL, primaryDateHeaderStyle=NULL, primaryDateHeaderUnit=NULL, resizingItemBorder=NULL, rightSidebarWidth=NULL, secondaryDateHeaderHeight=NULL, secondaryDateHeaderLabelFormat=NULL, secondaryDateHeaderStyle=NULL, secondaryDateHeaderUnit=NULL, selectedItemColor=NULL, showCursorMarker=NULL, showTodayMarker=NULL, sidebarHeaderContent=NULL, sidebarHeaderVariant=NULL, sidebarWidth=NULL, timeSteps=NULL, timelineHeaderStyle=NULL, todayMarkerInterval=NULL, todayMarkerStyle=NULL, traditionalZoom=NULL, useResizeHandle=NULL, visibleTimeEnd=NULL, visibleTimeStart=NULL, zoomData=NULL) {
    
    props <- list(id=id, boundsChangeData=boundsChangeData, buffer=buffer, canChangeGroup=canChangeGroup, canMove=canMove, canResize=canResize, canvasClickData=canvasClickData, canvasContextMenuData=canvasContextMenuData, canvasDoubleClickData=canvasDoubleClickData, clickTolerance=clickTolerance, cursorMarkerStyle=cursorMarkerStyle, customGroups=customGroups, customGroupsContent=customGroupsContent, customItems=customItems, customItemsContent=customItemsContent, customMarkers=customMarkers, defaultTimeEnd=defaultTimeEnd, defaultTimeStart=defaultTimeStart, disableScroll=disableScroll, dragInfoLabel=dragInfoLabel, dragInfoLabelStyle=dragInfoLabelStyle, dragSnap=dragSnap, draggingItemColor=draggingItemColor, groups=groups, groupsClass=groupsClass, groupsStyle=groupsStyle, itemClickData=itemClickData, itemContextMenuData=itemContextMenuData, itemDimensions=itemDimensions, itemDoubleClickData=itemDoubleClickData, itemHeightRatio=itemHeightRatio, itemSelectData=itemSelectData, itemTouchSendsClick=itemTouchSendsClick, items=items, itemsClass=itemsClass, itemsStyle=itemsStyle, lineHeight=lineHeight, maxZoom=maxZoom, minResizeWidth=minResizeWidth, minZoom=minZoom, primaryDateHeaderHeight=primaryDateHeaderHeight, primaryDateHeaderLabelFormat=primaryDateHeaderLabelFormat, primaryDateHeaderStyle=primaryDateHeaderStyle, primaryDateHeaderUnit=primaryDateHeaderUnit, resizingItemBorder=resizingItemBorder, rightSidebarWidth=rightSidebarWidth, secondaryDateHeaderHeight=secondaryDateHeaderHeight, secondaryDateHeaderLabelFormat=secondaryDateHeaderLabelFormat, secondaryDateHeaderStyle=secondaryDateHeaderStyle, secondaryDateHeaderUnit=secondaryDateHeaderUnit, selectedItemColor=selectedItemColor, showCursorMarker=showCursorMarker, showTodayMarker=showTodayMarker, sidebarHeaderContent=sidebarHeaderContent, sidebarHeaderVariant=sidebarHeaderVariant, sidebarWidth=sidebarWidth, timeSteps=timeSteps, timelineHeaderStyle=timelineHeaderStyle, todayMarkerInterval=todayMarkerInterval, todayMarkerStyle=todayMarkerStyle, traditionalZoom=traditionalZoom, useResizeHandle=useResizeHandle, visibleTimeEnd=visibleTimeEnd, visibleTimeStart=visibleTimeStart, zoomData=zoomData)
    if (length(props) > 0) {
        props <- props[!vapply(props, is.null, logical(1))]
    }
    component <- list(
        props = props,
        type = 'DashCalendarTimeline',
        namespace = 'dash_calendar_timeline',
        propNames = c('id', 'boundsChangeData', 'buffer', 'canChangeGroup', 'canMove', 'canResize', 'canvasClickData', 'canvasContextMenuData', 'canvasDoubleClickData', 'clickTolerance', 'cursorMarkerStyle', 'customGroups', 'customGroupsContent', 'customItems', 'customItemsContent', 'customMarkers', 'defaultTimeEnd', 'defaultTimeStart', 'disableScroll', 'dragInfoLabel', 'dragInfoLabelStyle', 'dragSnap', 'draggingItemColor', 'groups', 'groupsClass', 'groupsStyle', 'itemClickData', 'itemContextMenuData', 'itemDimensions', 'itemDoubleClickData', 'itemHeightRatio', 'itemSelectData', 'itemTouchSendsClick', 'items', 'itemsClass', 'itemsStyle', 'lineHeight', 'maxZoom', 'minResizeWidth', 'minZoom', 'primaryDateHeaderHeight', 'primaryDateHeaderLabelFormat', 'primaryDateHeaderStyle', 'primaryDateHeaderUnit', 'resizingItemBorder', 'rightSidebarWidth', 'secondaryDateHeaderHeight', 'secondaryDateHeaderLabelFormat', 'secondaryDateHeaderStyle', 'secondaryDateHeaderUnit', 'selectedItemColor', 'showCursorMarker', 'showTodayMarker', 'sidebarHeaderContent', 'sidebarHeaderVariant', 'sidebarWidth', 'timeSteps', 'timelineHeaderStyle', 'todayMarkerInterval', 'todayMarkerStyle', 'traditionalZoom', 'useResizeHandle', 'visibleTimeEnd', 'visibleTimeStart', 'zoomData'),
        package = 'dashCalendarTimeline'
        )

    structure(component, class = c('dash_component', 'list'))
}
